pom.xml
src/main/java/com/yunionyun/mcp/mcclient/keystone/BaseDomainResource.java
src/main/java/com/yunionyun/mcp/mcclient/keystone/Project.java
src/main/java/com/yunionyun/mcp/mcclient/keystone/TokenCredential.java
src/main/java/com/yunionyun/mcp/mcclient/keystone/User.java

Cherry pick of #1 on master.
#1: feat: 为Project对象添加domain属性，需要配合2.10.0版本后端使用

Automated cherry pick of #1: feat: 为Project对象添加domain属性，需要配合2.10.0版本后端使用

---

pom.xml
src/main/java/com/yunionyun/mcp/mcclient/keystone/BaseDomainResource.java
src/main/java/com/yunionyun/mcp/mcclient/keystone/Project.java
src/main/java/com/yunionyun/mcp/mcclient/keystone/TokenCredential.java
src/main/java/com/yunionyun/mcp/mcclient/keystone/User.java

原有的TokenCredential对象的getDomainId和getDomainName为获得用户的domain信息。

feat: 为Project对象添加domain属性，需要配合2.10.0版本后端使用

---

src/main/java/com/yunionyun/mcp/mcclient/managers/BaseManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/ImageQuotaManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/QuotaManager.java

**这个 PR 实现什么功能/修复什么问题:**
获得项目或者域的配额
**是否需要 backport 到之前的 release 分支:**
release/2.10.0
/cc @swordqiu

feat: 支持获取配额

---

src/main/java/com/yunionyun/mcp/mcclient/managers/BaseManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/ImageQuotaManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/QuotaManager.java

Cherry pick of #3 on release/2.10.0.
#3: feat: 支持获取配额

Automated cherry pick of #3: feat: 支持获取配额

---

src/main/java/com/yunionyun/mcp/mcclient/managers/impl/ImageQuotaManager.java

Cherry pick of #5 on release/2.10.0.
#5: fix: 修改镜像配额时镜像的body没有用quotas包一层

Automated cherry pick of #5: fix: 修改镜像配额时镜像的body没有用quotas包一层

---

pom.xml
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/ServerManager.java

添加修改主机配置接口
release/2.10.0
/cc @swordqiu

feat: 添加修改主机配置接口

---

pom.xml
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/ServerManager.java

Cherry pick of #7 on master.
#7: feat: 添加修改主机配置接口

Automated cherry pick of #7: feat: 添加修改主机配置接口

---

pom.xml
src/main/java/com/yunionyun/mcp/mcclient/AuthAgent.java
src/main/java/com/yunionyun/mcp/mcclient/Client.java

Cherry pick of #9 on release/2.10.0.
#9: feat: add auth operator

Automated cherry pick of #9: feat: add auth operator

---

.gitignore
pom.xml
src/main/java/com/yunionyun/mcp/mcclient/keystone/BaseDomainResource.java
src/main/java/com/yunionyun/mcp/mcclient/keystone/Project.java
src/main/java/com/yunionyun/mcp/mcclient/keystone/Service.java
src/main/java/com/yunionyun/mcp/mcclient/keystone/TokenCredential.java
src/main/java/com/yunionyun/mcp/mcclient/managers/BaseLogActionManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/BaseManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/BaseNotifyManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/ConfigManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/KeystoneManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/ResourceManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/CloudregionManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/GlanceManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/ImageQuotaManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/LogActionManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/NotifyManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/ParameterManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/ProjectManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/RoleAssignmentManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/RoleManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/ServerManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/SkuManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/UserManager.java

Cherry pick of #12 on release/2.7.0.
#12: 更改pox.xml中的version

Automated cherry pick of #12: 更改pox.xml中的version

---

pom.xml
src/main/java/com/yunionyun/mcp/mcclient/managers/BaseManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/ComputeManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/ResourceManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/GlanceManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/ImageQuotaManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/QuotaManager.java

由于配额的细分，同时返回类型发生变化，所以对相关的get方法和addquota方法进行了修改.
release/2.13

配额相关的几个manager的方法修改

---

pom.xml
src/main/java/com/yunionyun/mcp/mcclient/managers/BaseManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/ComputeManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/ResourceManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/GlanceManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/ImageQuotaManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/QuotaManager.java

Cherry pick of #14 on release/2.13.
#14: 配额相关的几个manager的方法修改

Automated cherry pick of #14: 配额相关的几个manager的方法修改

---

pom.xml

- 修改pom文件中的nexus仓库地址
release/2.13

修改pom文件中的nexus仓库地址

---

pom.xml

Cherry pick of #16 on release/2.13.
#16: 修改pom文件中的nexus仓库地址

Automated cherry pick of #16: 修改pom文件中的nexus仓库地址

---

pom.xml

修改pom文件，去掉ip地址的信息
- release/2.13

pom文件中涉及的地址修改

---

pom.xml

Cherry pick of #20 on release/2.13.
#20: pom文件中涉及的地址修改

Automated cherry pick of #20: pom文件中涉及的地址修改

---

pom.xml
src/main/java/com/yunionyun/mcp/mcclient/Session.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/BaremetalDiskConfig.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/CandidateDisk.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/CandidateNet.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/CandidateResource.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/DiskConfig.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/IsolatedDeviceConfig.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/NetworkConfig.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/SchedtagConfig.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/ScheduleInput.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/ScheduleOutput.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/SchedulerManager.java
src/test/java/com/yunionyun/mcp/mcclient/SchedulerManagerTest.java

在SchedulerManager中增加doForecast方法

---

src/main/java/com/yunionyun/mcp/mcclient/Session.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/BaremetalDiskConfig.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/CandidateDisk.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/CandidateNet.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/CandidateResource.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/DiskConfig.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/IsolatedDeviceConfig.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/NetworkConfig.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/SchedtagConfig.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/ScheduleInput.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/schedulermanager/ScheduleOutput.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/SchedulerManager.java
src/test/java/com/yunionyun/mcp/mcclient/SchedulerManagerTest.java

Cherry pick of #22 on release/2.13.
#22: 预调度

Automated cherry pick of #22: 在SchedulerManager中增加doForecast方法

---

src/main/java/com/yunionyun/mcp/mcclient/Utils.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/CloudregionManager.java
src/test/java/com/yunionyun/mcp/mcclient/CloudRegionManagerTest.java
src/test/java/com/yunionyun/mcp/mcclient/SkuManagerTest.java

Cherry pick of #24 on release/2.13.
#24: jsonObject 拼装参数改进

Automated cherry pick of #24: jsonObject 拼装参数改进

---

src/main/java/com/yunionyun/mcp/mcclient/Utils.java
src/main/java/com/yunionyun/mcp/mcclient/managers/GlanceManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/ImageQuotaManager.java
src/test/java/com/yunionyun/mcp/mcclient/NetworkManagerTest.java
src/test/java/com/yunionyun/mcp/mcclient/ServicesV3ManagerTest.java

当query 中 key | value == null 将会跳过拼装

调整query拼装url的逻辑

---

src/main/java/com/yunionyun/mcp/mcclient/managers/BaseManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/SchedulerManager.java
src/test/java/com/yunionyun/mcp/mcclient/SchedulerManagerTest.java

schedulerManager 中 doForecast 中逻辑

---

src/main/java/com/yunionyun/mcp/mcclient/managers/BaseManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/SchedulerManager.java
src/test/java/com/yunionyun/mcp/mcclient/SchedulerManagerTest.java

Cherry pick of #28 on release/2.13.
#28: schedulerManager 中 doForecast 中逻辑

Automated cherry pick of #28: schedulerManager 中 doForecast 中逻辑

---

pom.xml
src/main/java/com/yunionyun/mcp/mcclient/AuthAgent.java
src/main/java/com/yunionyun/mcp/mcclient/Client.java
src/main/java/com/yunionyun/mcp/mcclient/Session.java
src/main/java/com/yunionyun/mcp/mcclient/Utils.java
src/main/java/com/yunionyun/mcp/mcclient/entitys/RoleAssignmentsListInput.java
src/main/java/com/yunionyun/mcp/mcclient/managers/BaseManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/ComputeManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/GnocchiManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/ResourceManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/ImageQuotaManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/MeasuresManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/QuotaManager.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/RoleAssignmentManager.java
src/main/java/com/yunionyun/mcp/mcclient/utils/CodecUtils.java
src/test/java/com/yunionyun/mcp/mcclient/LogActionTest.java
src/test/java/com/yunionyun/mcp/mcclient/QuotaManagerTest.java
src/test/java/com/yunionyun/mcp/mcclient/SchedulerManagerTest.java
src/test/java/com/yunionyun/mcp/mcclient/ServerTest.java
src/test/java/com/yunionyun/mcp/mcclient/ServicesV3ManagerTest.java
src/test/java/com/yunionyun/mcp/mcclient/UserMangerTest.java

修改QuotaManager类

---

src/main/java/com/yunionyun/mcp/mcclient/keystone/Service.java
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/PriceInfoManager.java
src/main/java/com/yunionyun/mcp/mcclient/utils/pricespec/BaseResourceSpec.java
src/main/java/com/yunionyun/mcp/mcclient/utils/pricespec/CpuMemSpec.java
src/main/java/com/yunionyun/mcp/mcclient/utils/pricespec/DiskSpec.java
src/main/java/com/yunionyun/mcp/mcclient/utils/pricespec/InstanceDiskSpec.java
src/main/java/com/yunionyun/mcp/mcclient/utils/pricespec/InstanceSpec.java
src/main/java/com/yunionyun/mcp/mcclient/utils/pricespec/ResourceSpec.java
src/test/java/com/yunionyun/mcp/mcclient/PriceInfoTest.java

改进：增加获取价格的API支持
/cc @zhaoxiangchun

feature: add get price api

---

src/main/java/com/yunionyun/mcp/mcclient/utils/pricespec/DiskSpec.java
src/main/java/com/yunionyun/mcp/mcclient/utils/pricespec/InstanceSpec.java
src/main/java/com/yunionyun/mcp/mcclient/utils/pricespec/RdsCpuMemSpec.java
src/main/java/com/yunionyun/mcp/mcclient/utils/pricespec/RdsDiskSpec.java
src/main/java/com/yunionyun/mcp/mcclient/utils/pricespec/RdsSpec.java
src/main/java/com/yunionyun/mcp/mcclient/utils/pricespec/RedisSpec.java
src/test/java/com/yunionyun/mcp/mcclient/PriceInfoTest.java

add get price of rds and redis

---

README.md
src/main/java/com/yunionyun/mcp/mcclient/AuthAgent.java
src/main/java/com/yunionyun/mcp/mcclient/Client.java

fix: update README

---

pom.xml
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/webconsole/WebConsoleManager.java
src/test/java/com/yunionyun/mcp/mcclient/WebconsoleManagerTest.java

fix: support webconolse api of ssh and rdp

fix: support webconolse api of ssh and rdp

---

pom.xml
src/main/java/com/yunionyun/mcp/mcclient/managers/impl/cloudphone/PhoneAppManager.java

fix: add phone_apps manager
